version: "3"
services:
  client:
    image: opcua-client
    depends_on:
      - "server"
    volumes:
       - /home/melanie/Desktop/opcua/opcua-secure-example/client/secrets:/app/secrets
       
  server:
    image: opcua-server
    ports:
      - "4840:4840"
    volumes:
       - /home/melanie/Desktop/opcua/opcua-secure-example/server/certificates:/app/certificates
       
volumes:
    certificates:
    secrets: