version: "3"
services:
  client:
    image: opcua-client
    depends_on:
      - "server"
    volumes:
       - ./client/secrets:/app/secrets
       
  server:
    image: opcua-server
    ports:
      - "4840:4840"
    volumes:
       - ./server/certificates:/app/certificates
       
volumes:
    certificates:
    secrets: