version: "3"
services:
  client:
    image: opcua-client
    depends_on:
      - "server"
       
  server:
    image: opcua-server
    ports:
      - "4840:4840"
    volumes:
       - /home/melanie/Desktop/opcua/opcua-secure-example/server/credentials:/app/credentials
       
volumes:
    credentials: